SET check_function_bodies = false;
-- ddl-end --

CREATE SCHEMA MERAKI_DW_AIRFLOW_METADATA;
-- ddl-end --

SET search_path TO MERAKI_DW_AIRFLOW_METADATA;
-- ddl-end --

-- object: MERAKI_DW_AIRFLOW_METADATA.DAG_MASTER_SEQ | type: SEQUENCE --
-- DROP SEQUENCE MERAKI_DW_AIRFLOW_METADATA.DAG_MASTER_SEQ;
CREATE SEQUENCE MERAKI_DW_AIRFLOW_METADATA.DAG_MASTER_SEQ
	INCREMENT BY 1
	MINVALUE 0
	MAXVALUE 2147483647
	START WITH 1
	CACHE 1
	NO CYCLE
	OWNED BY NONE;
-- ddl-end --

-- object: MERAKI_DW_AIRFLOW_METADATA.TASK_TRACKER_SEQ | type: SEQUENCE --
-- DROP SEQUENCE MERAKI_DW_AIRFLOW_METADATA.TASK_TRACKER_SEQ;
CREATE SEQUENCE MERAKI_DW_AIRFLOW_METADATA.TASK_TRACKER_SEQ
	INCREMENT BY 1
	MINVALUE 0
	MAXVALUE 2147483647
	START WITH 1
	CACHE 1
	NO CYCLE
	OWNED BY NONE;
-- ddl-end --

-- ddl-end --
-- object: MERAKI_DW_AIRFLOW_METADATA.SRC_Config_Master_SEQ | type: SEQUENCE --
-- DROP SEQUENCE MERAKI_DW_AIRFLOW_METADATA.SRC_Config_Master_SEQ;
CREATE SEQUENCE MERAKI_DW_AIRFLOW_METADATA.SRC_Config_Master_SEQ
	INCREMENT BY 1
	MINVALUE 0
	MAXVALUE 2147483647
	START WITH 1
	CACHE 1
	NO CYCLE
	OWNED BY NONE;
-- ddl-end --

-- ddl-end --
-- object: MERAKI_DW_AIRFLOW_METADATA.TGT_Config_Master_SEQ | type: SEQUENCE --
-- DROP SEQUENCE MERAKI_DW_AIRFLOW_METADATA.TGT_Config_Master_SEQ;
CREATE SEQUENCE MERAKI_DW_AIRFLOW_METADATA.TGT_Config_Master_SEQ
	INCREMENT BY 1
	MINVALUE 0
	MAXVALUE 2147483647
	START WITH 1
	CACHE 1
	NO CYCLE
	OWNED BY NONE;
-- ddl-end --


-- object: MERAKI_DW_AIRFLOW_METADATA.DAG_RUN_MASTER | type: TABLE --
-- DROP TABLE MERAKI_DW_AIRFLOW_METADATA.DAG_RUN_MASTER;
CREATE TABLE DAG_RUN_MASTER (
	,DAG_MASTER_NO bigint NOT NULL DEFAULT nextval('MERAKI_DW_AIRFLOW_METADATA.DAG_MASTER_SEQ'::regclass)
    ,DDAG_NAME	VARCHAR(20)
    ,DAG_ID	VARCHAR(20)
    ,RUN_DT DATE	TIMESTAMP NOT NULL
    ,START_TIME TIMESTAMP NOT NULL
    ,END_TIME  TIMESTAMP NOT NULL
	CONSTRAINT PK_DAG_MASTER_NO PRIMARY KEY (DAG_MASTER_NO) 
);


-- object: MERAKI_DW_AIRFLOW_METADATA.DAG_RUN_TASK_TRACKER | type: TABLE --
-- DROP TABLE MERAKI_DW_AIRFLOW_METADATA.DAG_RUN_TASK_TRACKER;
CREATE TABLE DAG_RUN_TASK_TRACKER (
	 TASK_TRACKER_NO bigint NOT NULL DEFAULT nextval('MERAKI_DW_AIRFLOW_METADATA.TASK_TRACKER_SEQ'::regclass)
    ,DAG_MASTER_NO VARCHAR(20)
    ,DAG_ID	VARCHAR(20)
    ,TASK_ID	VARCHAR(20)
    ,RUN_DT	TIMESTAMP NOT NULL
    ,RUN_NO	NUMBER NOT NULL
    ,START_TIME	TIMESTAMP NOT NULL
    ,END_TIME	TIMESTAMP NOT NULL
    ,SRC_CONFIG_MASTER_KEY	Number 
    ,REC_COUNT_ON_READ	Number
    ,REC_COUNT_ON_WRITE	Number 
	,CONSTRAINT pk_TASK_TRACKER PRIMARY KEY (TASK_TRACKER_NO)
    );
-- ddl-end --

-- object: fk_DAG_MASTER | type: CONSTRAINT --
-- ALTER TABLE MERAKI_DW_AIRFLOW_METADATA.DAG_RUN_TASK_TRACKER DROP CONSTRAINT fk_DAG_MASTER;
ALTER TABLE MERAKI_DW_AIRFLOW_METADATA.DAG_RUN_TASK_TRACKER ADD CONSTRAINT fk_DAG_MASTER FOREIGN KEY (DAG_MASTER_NO)
REFERENCES MERAKI_DW_AIRFLOW_METADATA.DAG_RUN_MASTER (DAG_MASTER_NO) MATCH FULL
ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_SRC_CONFIG_MASTER | type: CONSTRAINT --
-- ALTER TABLE MERAKI_DW_AIRFLOW_METADATA.DAG_RUN_TASK_TRACKER DROP CONSTRAINT fk_SRC_CONFIG_MASTER;
ALTER TABLE MERAKI_DW_AIRFLOW_METADATA.DAG_RUN_TASK_TRACKER ADD CONSTRAINT fk_SRC_CONFIG_MASTER FOREIGN KEY (SRC_CONFIG_MASTER_KEY)
REFERENCES MERAKI_DW_AIRFLOW_METADATA.SRC_CONFIG_MASTER (SRC_CONFIG_MASTER_KEY) MATCH FULL
ON DELETE CASCADE ON UPDATE NO ACTION;


------ STATIC TABLE ---  Maintained externally, not maintained through DAG - READONLY
-- object: MERAKI_DW_AIRFLOW_METADATA.SRC_CONFIG_MASTER | type: TABLE --
-- DROP TABLE MERAKI_DW_AIRFLOW_METADATA.SRC_CONFIG_MASTER;
CREATE TABLE SRC_CONFIG_MASTER ( 
 SRC_Config_Master_key	bigint NOT NULL DEFAULT nextval('MERAKI_DW_AIRFLOW_METADATA.SRC_Config_Master_SEQ'::regclass)
,DAG_NAME	            VARCHAR(20)
,SRC_SYSTEM	            VARCHAR(20)
,SRC_DATABASE	        VARCHAR(20)
,SRC_SCHEMA	            VARCHAR(20)
,SRC_TABLE	            VARCHAR(20)
,SRC_Fields	            VARCHAR(250)
,SRC_Field_Version_No	Number
,SRC_TBL_TYPE	        VARCHAR(20)
,ACTIVE_IND	            Char(1)
,START_DATE	            TIMESTAMP NOT NULL
,END_DATE               TIMESTAMP NOT NULL
,CREATE_DATE	        TIMESTAMP NOT NULL
,CREATED_BY	            VARCHAR(20)
,MODIFIED_DATE	        TIMESTAMP NOT NULL
,MODIFIED_BY	        Varchar(20)
,CONSTRAINT pk_SRC_Config_Master PRIMARY KEY (SRC_Config_Master_key)
)

------ STATIC TABLE ---  Maintained externally, not maintained through DAG - READONLY
-- object: MERAKI_DW_AIRFLOW_METADATA.TGT_CONFIG_MASTER | type: TABLE --
-- DROP TABLE MERAKI_DW_AIRFLOW_METADATA.TGT_CONFIG_MASTER;
CREATE TABLE TGT_CONFIG_MASTER ( 
TGT_Config_Master_key	bigint NOT NULL DEFAULT nextval('MERAKI_DW_AIRFLOW_METADATA.TGT_Config_Master_SEQ'::regclass)
,DAG_NAME	            VARCHAR(20)
,TGT_SYSTEM	            VARCHAR(20)
,TGT_DATABASE	        VARCHAR(20)
,TGT_SCHEMA	            VARCHAR(20)
,TGT_TABLE	            VARCHAR(20)
,TGT_Fields	            VARCHAR(250)
,TGT_Field_Version_No	Number
,TGT_TBL_TYPE	        VARCHAR(20)
,ACTIVE_IND	            Char(1)
,START_DATE	            TIMESTAMP NOT NULL
,END_DATE               TIMESTAMP NOT NULL
,CREATE_DATE	        TIMESTAMP NOT NULL
,CREATED_BY	            VARCHAR(20)
,MODIFIED_DATE	        TIMESTAMP NOT NULL
,MODIFIED_BY	        Varchar(20)
,CONSTRAINT pk_TGT_Config_Master PRIMARY KEY (TGT_Config_Master_key)
)

